name: Weather Kisht Bot

on: [push]
jobs:
  GitHub_Good_day_Actions:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Dependencies
            run: pip install -r requirements.txt
          - name: Rum code
            run: python app.py