name: Weather Kisht Bot

on: [push]
env:
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
jobs:
  GitHub_Good_day_Actions:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Dependencies
            run: pip install -r requirements.txt
          - name: Rum code
            run: python app.py